### ISSUE TITLE
Issue in ProbablesStats2022

### ISSUE THREAD

**Issue by obecerra-dimeline** [Michael-Goldfarb/MLBGamePredictor#3]
There is an issue in the code:

`/ProbablesStats2022.py", line 167, in <module>
    cursor.close()
    ^^^^^^
NameError: name 'cursor' is not defined
(mlbgamepredictor) (base) newuser@news-MacBook-Pro PastTables % python3 ProbablesStats2022.py
An error occurred: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

Traceback (most recent call last):
  File "./MLBGamePredictor/Tables/PastTables/ProbablesStats2022.py", line 167, in <module>
    cursor.close()
    ^^^^^^
NameError: name 'cursor' is not defined`

**Comment by Michael-Goldfarb** [comment]
Are you following Notes.md? And if so, did the other tables work correctly?

**Comment by obecerra-dimeline** [comment]
I am following the Notes.md yes and yes the others worked correctly, I am just building the last one ProbablesStats2022.py and that's the only one with an error

**Comment by Michael-Goldfarb** [comment]
Try re inputting your database credentials in your terminal and running the file again

**Comment by obecerra-dimeline** [comment]
Here is more info on the error::

An error occurred: could not translate host name "bubble.db.elephantsql.com" to address: nodename nor servname provided, or not known

Traceback (most recent call last):
  File "./MLBGamePredictor/Tables/PastTables/ProbablesStats2022.py", line 172, in <module>
    cursor.close()
    ^^^^^^
NameError: name 'cursor' is not defined

this is the same host I use on all the other ones and it worked
